# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wcY4fyE1hMGSJfIm5DZgWxwb6SPXALeV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("/content/drive/MyDrive/transport dataset.csv")

x = np.linspace(0, 5, 11)
y = x**2

x

y

plt.plot(x, y)
plt.show()

plt.xlabel('X values')
plt.ylabel('Y values')
plt.title('Graph of $y = x^2$')

plt.plot(x, y)
plt.show()

x1 = np.linspace(-np.pi, np.pi, 256)
x2 = np.linspace(-np.pi, np.pi, 256)

y1 = np.cos(x1)
y2 = np.sin(x2)

print(x1)

plt.plot(x1, y1, x2, y2)
plt.show()

plt.figure(figsize = (10, 6), dpi = 80)

plt.plot(x1, y1)
plt.plot(x2, y2)

plt.show()

plt.figure(figsize = (10, 6), dpi = 80)

plt.plot(x1, y1, 'r-.')
plt.plot(x2, y2, 'b--')

plt.show()

plt.figure(figsize = (10, 6), dpi = 80)

plt.plot(x1, y1, color = 'purple')
plt.plot(x2, y2, color = 'green')

plt.show()

plt.figure(figsize = (10, 6), dpi = 80)

plt.plot(x1, y1, color = 'purple', lw = 2.5)
plt.plot(x2, y2, color = 'green', lw = 2.5)

plt.show()

plt.figure(figsize = (10, 6), dpi = 80)

plt.plot(x1, y1, color = 'purple', lw = 2.5, ls = '--')
plt.plot(x2, y2, color = 'green', lw = 2.5, ls = '-.')

plt.show()

plt.figure(figsize = (10, 6), dpi = 80)

plt.plot(x1, y1, color = 'purple', lw = 2.5, ls = '--')
plt.plot(x2, y2, color = 'green', lw = 2.5, ls = '-.')

plt.xticks([-np.pi, -np.pi/2, 0, np.pi/2, np.pi])
plt.yticks([-1, 0, 1])

plt.show()

hours = df["Usage_Hours"]
capacity = df["Load_Capacity"]

import matplotlib.pyplot as plt

plt.scatter(hours, capacity)
plt.xlabel("Usage Hours")
plt.ylabel("Load Capacity")
plt.show()

counts = df["Vehicle_Type"].value_counts()

plt.figure()
plt.pie(counts, labels=counts.index, autopct='%1.1f%%')
plt.title("Vehicle Type Distribution")
plt.show()

plt.figure()
plt.plot(df["Vehicle_ID"], df["Usage_Hours"], marker='o')

plt.xlabel("Vehicle ID")
plt.ylabel("Usage Hours")
plt.title("Usage Hours Trend")

plt.show()

avg_load = df.groupby("Vehicle_Type")["Load_Capacity"].mean()

plt.figure()
plt.bar(avg_load.index, avg_load.values)

plt.xlabel("Vehicle Type")
plt.ylabel("Average Load Capacity")
plt.title("Average Load Capacity by Type")

plt.show()

plt.figure()
plt.hist(df["Usage_Hours"], bins=5)

plt.xlabel("Usage Hours")
plt.ylabel("Frequency")
plt.title("Usage Hours Distribution")

plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("/content/drive/MyDrive/transport dataset.csv")
df.columns = df.columns.str.strip()

plt.bar(df['Vehicle_Type'], df['Maintenance_Cost'], color='green')
plt.xlabel('Vehicle Type')
plt.ylabel('Maintenance Cost')
plt.title('Maintenance Cost by Vehicle Type')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

colors = plt.cm.viridis(np.linspace(0,1,len(df)))

plt.bar(df['Vehicle_ID'], df['Maintenance_Cost'], color=colors)
plt.show()

plt.figure(figsize=(10,8))

plt.subplot(2,2,1)
plt.bar(df['Vehicle_ID'], df['Maintenance_Cost'])
plt.title("Maintenance Cost")

plt.subplot(2,2,2)
plt.plot(df['Usage_Hours'], df['Fuel_Consumption'])
plt.title("Fuel vs Usage")

plt.bar(df['Vehicle_ID'], df['Maintenance_Cost'], alpha=0.6, label='Cost')
plt.plot(df['Vehicle_ID'], df['Predictive_Score'], color='red', marker='o', label='Score')

plt.legend()
plt.show()

fig = plt.figure(figsize=(12,6))
axes = fig.subplots(2, 3)

axes[0][0].plot(df['Usage_Hours'], df['Fuel_Consumption'], 'r--')
axes[0][0].set_title('Usage vs Fuel')

axes[0][1].plot(df['Usage_Hours'], df['Maintenance_Cost'], 'b-.')
axes[0][1].set_title('Usage vs Cost')

axes[0][2].scatter(df['Vehicle_ID'], df['Predictive_Score'])
axes[0][2].set_title('Predictive Score')

axes[1][0].hist(df['Maintenance_Cost'])
axes[1][0].set_title('Cost Distribution')

axes[1][1].plot(df['Usage_Hours'], df['Impact_on_Efficiency'], 'g--')
axes[1][1].set_title('Efficiency Impact')

axes[1][2].bar(df['Vehicle_ID'], df['Downtime_Maintenance'])
axes[1][2].set_title('Downtime')


fig.tight_layout()
plt.show()

num_df = df.select_dtypes(include=['number'])

plt.figure(figsize=(10,8))

sns.heatmap(num_df.corr(), annot=True, cmap='coolwarm')

plt.title("Vehicle Dataset Correlation Heatmap")
plt.show()











